excerpt_separator: ""
pygments: true
markdown: kramdown
highlighter: rouge
url: http://howardzhang.github.io
title: Hou Wa Cheung's Blog
tagline: A log of everyday life
description: My awesome new site
paginate: 5
timezone: CH
