excerpt_separator: ""

highlighter: rouge
gems: [jekyll-paginate]

url: https://howardzhang.github.io
title: Hou Wa Cheung's Blog
tagline: lifelong learning, writing to learn
description: lifelong learning, writing to learn
paginate: 5
#paginate_path: '/blog/page:num'
timezone: CH
permalink: pretty
version: 1.0.0
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"

sass:
  style: compressed
  sass_dir: _scss

author:
  name: Cheung Hou Wa
  description: A passionate <strong>developer</strong>, lifelong learning.
  gravatar: 8fcdcec2676d70c15efa28bd27919537
nav:
  Home:
    - '/'
  Categories:
    - '/categories/'
  Tags:
    - '/tags/'
  About:
    - '/about/'
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

mathjax: true
google_analytics_token:
disqus_short_name:
